### ISSUE TITLE
Add stan bayes activity to exercise folder

### ISSUE THREAD

**Issue by kbbodner** [kbbodner/cefi_shortcourse_students_2023#7]
Please can you upload the R code for the Bayesian stan exercise for tomorrow (Monday). We could label it Activity_01_STAN_Primer.Rmd to match the jags version.

**Comment by kbbodner** [comment]
Not sure who last worked with it last so have added both you two @sempwn and @colebrookson to the issue. Thanks!

**Comment by sempwn** [comment]
Added in [3b8ac32](https://github.com/kbbodner/cefi_shortcourse_students_2023/commit/3b8ac32e7e51fe2887d6bffe816f373bce0caabc)
